name: Publish

on: [push]

jobs:
  unit-test:
    name: Unit test distribution 🧪
    runs-on: ubuntu-latest
    env:
      YEAR: ${{ secrets.YEAR }}
      AOC_SESSION: ${{ secrets.AOC_SESSION }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Run Unit tests
      run: |
        pip install -r requirements-dev.txt
        pip install -r requirements.txt
        python -m pytest
